Repository CA-G12/EmojisHub, pull requests merged in 2022-09, with the labels that each got.

#10 add file structure
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: merged

#11 3 create data file
  src/components/.gitkeep
  src/data/data.json
Labels: merged

#12 create axios requests
  package-lock.json
  package.json
  src/App.js
  src/helpers/requests.js
Labels: merged

#13 5 handle result component
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/emoji.jsx
  src/components/results.jsx
  src/components/sidebar.jsx
  src/helpers/requests.js
Labels: approved

#15 handle copy icons
  src/App.css
  src/components/emoji.jsx
  src/components/results.jsx
Labels: awaiting-review

#16 handle copied message
  src/App.css
  src/components/emoji.jsx
Labels: approved

#17 Sidebar
  README.md
  package-lock.json
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/components/.gitkeep
  src/components/Results/emoji.jsx
  src/components/Results/results.jsx
  src/components/Sidebar/Categoty.js
  src/components/Sidebar/Sidebar.js
  src/components/emoji.jsx
  src/components/results.jsx
  src/components/sidebar.jsx
  src/helpers/requests.js
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: approved

#21 handle favorite icon
  src/App.css
  src/components/Results/emoji.jsx
Labels: awaiting-review

#22 Handled adding and removing from favorites
  src/components/Results/emoji.jsx
  src/components/Results/results.jsx
Labels: todo

#25 Favicon
  public/favicon.ico
  public/index.html
  src/App.css
  src/components/Sidebar/Sidebar.js
Labels: todo

#28 Fixing bugs
  src/App.css
  src/components/Results/emoji.jsx
  src/components/Results/results.jsx
  src/components/Sidebar/Categoty.js
  src/components/Sidebar/Sidebar.js
Labels: approved

#29 Fixing bugs
  src/App.css
  src/components/Results/emoji.jsx
  src/components/Results/results.jsx
Labels: approved
